[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"
evm_version = 'paris' 
optimizer = true
optimizer_runs = 200

fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 1024

[rpc_endpoints]
bscMainnet = "https://bsc-dataseed.binance.org/"
bscTestnet = "https://data-seed-prebsc-1-s1.binance.org:8545"

[etherscan]
bscMainnet = { key = "${BSCSCAN_API_KEY}", chain = 56, url = "https://api.bscscan.com/api" }
bscTestnet = { key = "${BSCSCAN_API_KEY}", chain = 97, url = "https://api-testnet.bscscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config